"""Plan-level execution settings for PSU authorisation steps.

The canonical test plan may declare an optional ``execution`` block::

    "execution": {
        "psuAuthorization": {
            "mode": "auto-approve",
            "headers": {"X-Sandbox-Auto-Approve": "true"},
            "parameters": {"sandbox_auto_approve": true}
        }
    }

``mode`` selects who completes OAuth 2.0 PSU authorisation steps: with
``manual`` the PSU does, in a browser, and the runner waits for the
``redirect_uri`` callback; with ``auto-approve`` the sandbox does. The runner
sends the authorisation request with an HTTP client (not a browser) and
expects the ASPSP to approve automatically and redirect straight back to
``redirect_uri``; login and consent pages are not automated. Ozone and the
legacy FCS call this facility "headless". Auto-approval is a sandbox test
facility, not an Open Banking UK or FAPI concept. Header and parameter names are participant
defined because sandbox auto-approval facilities are ASPSP-specific; they are
not Open Banking UK standard fields and do not by themselves evidence PSU
authentication, consent interaction, or SCA.

* ``headers`` are attached only to the auto-approve PSU authorisation request. A
  normal browser link cannot carry headers, so non-empty headers are rejected
  in ``manual`` mode.
* ``parameters`` apply in both modes and only to the PSU authorisation
  request. FAPI 1 Advanced Part 2 §5.2.2 requires the authorisation server to
  use only parameters carried inside the signed request object, so the
  executor embeds them as request-object claims whenever a request object is
  used, and appends them to the query string only for steps without one.

Names that the runner owns (OAuth/OIDC/JAR fields and HTTP framing headers)
are reserved so custom configuration cannot override tool-managed security
values. Headers are never translated into parameters or vice versa.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Final, Literal

from conformance.json_types import JsonObject, JsonValue

PsuAuthorizationModeSetting = Literal["manual", "auto-approve"]
"""Plan-level PSU authorisation mode."""

type PsuParameterValue = str | int | float | bool
"""Accepted JSON scalar types for custom PSU authorisation parameters."""

RESERVED_PSU_PARAMETER_NAMES: Final[frozenset[str]] = frozenset(
    {
        "aud",
        "claims",
        "client_id",
        "code_challenge",
        "code_challenge_method",
        "exp",
        "iat",
        "iss",
        "jti",
        "nbf",
        "nonce",
        "openbanking_intent_id",
        "redirect_uri",
        "request",
        "request_uri",
        "response_mode",
        "response_type",
        "scope",
        "state",
        "sub",
    }
)
"""OAuth 2.0 / OIDC / JAR fields generated by the runner (compared lower-case)."""

RESERVED_PSU_HEADER_NAMES: Final[frozenset[str]] = frozenset(
    {
        "connection",
        "content-length",
        "host",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "proxy-connection",
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
    }
)
"""HTTP framing and hop-by-hop headers managed by the HTTP client (lower-case)."""

_HEADER_NAME_PATTERN: Final = re.compile(r"^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$")
"""RFC 9110 ``token`` grammar for header field names."""

_PARAMETER_NAME_PATTERN: Final = re.compile(r"^[A-Za-z0-9_.\-~:]+$")
"""Conservative URL-safe grammar for custom authorisation parameter names."""

_MAX_NAME_LENGTH: Final = 128
_MAX_VALUE_LENGTH: Final = 4096
_MAX_ENTRIES: Final = 32

_EXECUTION_KEYS: Final = frozenset({"psuAuthorization"})
_PSU_AUTHORIZATION_KEYS: Final = frozenset({"mode", "headers", "parameters"})
_RESERVED_EXECUTION_KEYS: Final = frozenset({"resourceRequests"})
"""Execution keys reserved for future scoped configuration (not yet supported)."""


class ExecutionSettingsError(ValueError):
    """Raised when a plan ``execution`` block is malformed or unsafe."""


@dataclass(frozen=True)
class PsuAuthorizationSettings:
    """Plan-level configuration applied to every PSU authorisation step.

    Attributes:
        mode: ``manual`` (browser hand-off and callback) or ``auto-approve``
            (runner-issued authorisation GET).
        headers: Ordered custom header name/value pairs for the auto-approve
            authorisation request only.
        parameters: Ordered custom authorisation parameter name/value pairs.
    """

    mode: PsuAuthorizationModeSetting = "manual"
    headers: tuple[tuple[str, str], ...] = ()
    parameters: tuple[tuple[str, PsuParameterValue], ...] = ()

    @property
    def is_default(self) -> bool:
        """Return whether the settings equal the implicit default.

        Returns:
            ``True`` for manual mode without custom headers or parameters.
        """
        return self.mode == "manual" and not self.headers and not self.parameters

    def to_json_object(self) -> JsonObject:
        """Serialise to the canonical ``execution.psuAuthorization`` shape.

        Returns:
            JSON object including only non-empty optional sections.
        """
        body: JsonObject = {"mode": self.mode}
        if self.headers:
            body["headers"] = dict(self.headers)
        if self.parameters:
            body["parameters"] = dict(self.parameters)
        return body

    def evidence(self) -> JsonObject:
        """Return result evidence naming configured values without disclosing them.

        Returns:
            JSON object with the mode and configured header/parameter names.
        """
        return {
            "mode": self.mode,
            "headerNames": [name for name, _value in self.headers],
            "parameterNames": [name for name, _value in self.parameters],
        }


@dataclass(frozen=True)
class PlanExecutionSettings:
    """Typed representation of the optional canonical ``execution`` block.

    Attributes:
        psu_authorization: PSU authorisation settings.
    """

    psu_authorization: PsuAuthorizationSettings = field(default_factory=PsuAuthorizationSettings)

    @property
    def is_default(self) -> bool:
        """Return whether every section equals its implicit default.

        Returns:
            ``True`` when the block can be omitted from exports.
        """
        return self.psu_authorization.is_default

    def to_json_object(self) -> JsonObject:
        """Serialise to the canonical ``execution`` JSON shape.

        Returns:
            JSON object for the plan's ``execution`` key.
        """
        return {"psuAuthorization": self.psu_authorization.to_json_object()}


DEFAULT_EXECUTION_SETTINGS: Final = PlanExecutionSettings()
"""Implicit settings used when a plan omits ``execution``."""


def parse_execution_settings(raw: object, *, location: str = "testPlan.execution") -> PlanExecutionSettings:
    """Parse and validate a canonical ``execution`` block.

    Args:
        raw: Decoded ``execution`` JSON value.
        location: Dot-path used in error messages.

    Returns:
        Validated execution settings.

    Raises:
        ExecutionSettingsError: If the block is malformed, uses reserved
            names, duplicates names, or supplies headers in manual mode.
    """
    if not isinstance(raw, dict):
        raise ExecutionSettingsError(f"{location} must be an object")
    for key in raw:
        if key in _RESERVED_EXECUTION_KEYS:
            raise ExecutionSettingsError(f"{location}.{key} is reserved and not yet supported")
        if key not in _EXECUTION_KEYS:
            raise ExecutionSettingsError(f"{location} contains unsupported key: {key}")
    raw_psu = raw.get("psuAuthorization")
    if raw_psu is None:
        return PlanExecutionSettings()
    return PlanExecutionSettings(
        psu_authorization=parse_psu_authorization_settings(raw_psu, location=f"{location}.psuAuthorization")
    )


def parse_psu_authorization_settings(raw: object, *, location: str) -> PsuAuthorizationSettings:
    """Parse and validate an ``execution.psuAuthorization`` object.

    Args:
        raw: Decoded JSON value.
        location: Dot-path used in error messages.

    Returns:
        Validated PSU authorisation settings.

    Raises:
        ExecutionSettingsError: If the object is malformed or unsafe.
    """
    if not isinstance(raw, dict):
        raise ExecutionSettingsError(f"{location} must be an object")
    unknown = sorted(set(raw) - _PSU_AUTHORIZATION_KEYS)
    if unknown:
        raise ExecutionSettingsError(f"{location} contains unsupported key(s): {', '.join(unknown)}")
    raw_mode = raw.get("mode", "manual")
    if raw_mode == "headless":
        raise ExecutionSettingsError(
            f"{location}.mode 'headless' has been renamed to 'auto-approve'. Update the plan's execution settings"
        )
    if raw_mode not in ("manual", "auto-approve"):
        raise ExecutionSettingsError(f"{location}.mode must be one of: manual, auto-approve")
    mode: PsuAuthorizationModeSetting = "auto-approve" if raw_mode == "auto-approve" else "manual"
    headers = validate_psu_headers(_pairs(raw.get("headers"), location=f"{location}.headers"), location=location)
    parameters = validate_psu_parameters(
        _pairs(raw.get("parameters"), location=f"{location}.parameters"),
        location=location,
    )
    if mode == "manual" and headers:
        raise ExecutionSettingsError(
            f"{location}.headers cannot be used in manual mode: a browser authorisation link cannot carry "
            "custom headers. Use mode 'auto-approve' or remove the headers."
        )
    return PsuAuthorizationSettings(mode=mode, headers=headers, parameters=parameters)


def validate_psu_headers(
    pairs: tuple[tuple[str, JsonValue], ...],
    *,
    location: str,
) -> tuple[tuple[str, str], ...]:
    """Validate custom PSU authorisation header name/value pairs.

    Args:
        pairs: Ordered raw header name/value pairs.
        location: Dot-path of the owning ``psuAuthorization`` object.

    Returns:
        Validated header pairs.

    Raises:
        ExecutionSettingsError: If a name is invalid, reserved, or duplicated
            (case-insensitively), or a value is not a safe string.
    """
    _check_entry_count(pairs, location=f"{location}.headers")
    seen: set[str] = set()
    validated: list[tuple[str, str]] = []
    for name, value in pairs:
        label = f"{location}.headers[{name!r}]"
        _check_name(name, pattern=_HEADER_NAME_PATTERN, label=label, kind="header")
        lower = name.lower()
        if lower in RESERVED_PSU_HEADER_NAMES:
            raise ExecutionSettingsError(f"{label} is managed by the HTTP client and cannot be overridden")
        if lower in seen:
            raise ExecutionSettingsError(f"{label} duplicates another header name (names are case-insensitive)")
        seen.add(lower)
        if not isinstance(value, str):
            raise ExecutionSettingsError(f"{label} value must be a string")
        _check_value_text(value, label=label)
        validated.append((name, value))
    return tuple(validated)


def validate_psu_parameters(
    pairs: tuple[tuple[str, JsonValue], ...],
    *,
    location: str,
) -> tuple[tuple[str, PsuParameterValue], ...]:
    """Validate custom PSU authorisation parameter name/value pairs.

    Args:
        pairs: Ordered raw parameter name/value pairs.
        location: Dot-path of the owning ``psuAuthorization`` object.

    Returns:
        Validated parameter pairs.

    Raises:
        ExecutionSettingsError: If a name is invalid, reserved, or duplicated,
            or a value is not a JSON string, number, or boolean.
    """
    _check_entry_count(pairs, location=f"{location}.parameters")
    seen: set[str] = set()
    validated: list[tuple[str, PsuParameterValue]] = []
    for name, value in pairs:
        label = f"{location}.parameters[{name!r}]"
        _check_name(name, pattern=_PARAMETER_NAME_PATTERN, label=label, kind="parameter")
        lower = name.lower()
        if lower in RESERVED_PSU_PARAMETER_NAMES:
            raise ExecutionSettingsError(f"{label} is generated by the runner and cannot be overridden")
        if lower in seen:
            raise ExecutionSettingsError(f"{label} duplicates another parameter name")
        seen.add(lower)
        if isinstance(value, bool | int | float):
            validated.append((name, value))
            continue
        if not isinstance(value, str):
            raise ExecutionSettingsError(f"{label} value must be a string, number, or boolean")
        _check_value_text(value, label=label)
        validated.append((name, value))
    return tuple(validated)


def parameter_query_value(value: PsuParameterValue) -> str:
    """Render a custom parameter value for an ``application/x-www-form-urlencoded`` query.

    Args:
        value: Validated parameter value.

    Returns:
        String form using JSON spelling for booleans.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _pairs(raw: object, *, location: str) -> tuple[tuple[str, JsonValue], ...]:
    """Return ordered name/value pairs from an optional JSON object.

    Args:
        raw: Optional decoded JSON object.
        location: Dot-path used in error messages.

    Returns:
        Ordered pairs, or an empty tuple when ``raw`` is ``None``.

    Raises:
        ExecutionSettingsError: If ``raw`` is present but not an object.
    """
    if raw is None:
        return ()
    if not isinstance(raw, Mapping):
        raise ExecutionSettingsError(f"{location} must be an object of name/value pairs")
    return tuple((str(name), value) for name, value in raw.items())


def _check_entry_count(pairs: tuple[tuple[str, JsonValue], ...], *, location: str) -> None:
    """Reject oversized custom configuration.

    Args:
        pairs: Pairs to count.
        location: Dot-path used in error messages.

    Raises:
        ExecutionSettingsError: If more than the supported number of entries is supplied.
    """
    if len(pairs) > _MAX_ENTRIES:
        raise ExecutionSettingsError(f"{location} supports at most {_MAX_ENTRIES} entries")


def _check_name(name: str, *, pattern: re.Pattern[str], label: str, kind: str) -> None:
    """Validate a custom header or parameter name.

    Args:
        name: Candidate name.
        pattern: Allowed grammar.
        label: Error-message label.
        kind: ``header`` or ``parameter`` for messages.

    Raises:
        ExecutionSettingsError: If the name is blank, too long, or not allowed.
    """
    if not name or len(name) > _MAX_NAME_LENGTH or pattern.fullmatch(name) is None:
        raise ExecutionSettingsError(f"{label} is not a valid {kind} name")


def _check_value_text(value: str, *, label: str) -> None:
    """Reject values that could split headers or exceed sane bounds.

    Args:
        value: Candidate string value.
        label: Error-message label.

    Raises:
        ExecutionSettingsError: If the value contains control characters or is too long.
    """
    if len(value) > _MAX_VALUE_LENGTH:
        raise ExecutionSettingsError(f"{label} value exceeds {_MAX_VALUE_LENGTH} characters")
    if any(ord(character) < 0x20 and character != "\t" or ord(character) == 0x7F for character in value):
        raise ExecutionSettingsError(f"{label} value must not contain control characters")
