"""Schema-version 2.0 configuration contracts and runtime preparation."""

from conformance.configuration_contracts.compiled_plan_adapter import (
    LegacyExecutionEngine,
    PreparedExecutionManifest,
    ResolvedPlanAdapterError,
    validate_execution_manifest_compatibility,
)
from conformance.configuration_contracts.diagnostics import (
    ConfigurationContractError,
    ConfigurationDiagnostic,
    DiagnosticCode,
    DiagnosticSeverity,
)
from conformance.configuration_contracts.models import (
    ArtifactReference,
    Capability,
    CompilationFinding,
    DetachedJwsOmittedClaim,
    DetachedJwsProfile,
    DetachedJwsSource,
    Endpoint,
    EvidenceMode,
    ExecutionDetachedJws,
    ExecutionEvidencePolicy,
    ExecutionManifestAssertion,
    ExecutionManifestHeader,
    ExecutionManifestInput,
    ExecutionManifestRequest,
    ExecutionPsuAuthorization,
    ExecutionResponseSignature,
    ExecutionTokenEndpointAuth,
    FindingSeverity,
    FindingSourceDocument,
    GeneratedHeaderValue,
    GeneratedValueStrategy,
    HttpMethod,
    InputResolutionSource,
    ParticipantExecutionConfiguration,
    ParticipantInput,
    PredefinedInput,
    PredefinedInputValue,
    RequestBaseUrlSource,
    RequestInputBinding,
    RequestModification,
    RequestStateBinding,
    ResolutionReason,
    ResolvedCapability,
    ResponseSignatureSource,
    SelectionOrigin,
    Sha256Digest,
    StableId,
    StandingOrderFrequency,
    SuiteRelease,
    TechnicalSource,
    TestAssertion,
    TestOutput,
    TokenEndpointAuthSource,
    ToolRelease,
)
from conformance.configuration_contracts.suite_release_artifacts import (
    ResolvedSuiteArtifact,
    SuiteReleaseArtifactError,
    SuiteReleaseArtifactErrorCode,
    SuiteReleaseArtifactResolver,
    preflight_suite_release_artifacts,
)
from conformance.configuration_contracts.v2_compiler import (
    CompilationFindingCode,
    ParticipantPlanCompilationError,
    compile_participant_plan,
    resolve_participant_plan,
)
from conformance.configuration_contracts.v2_execution_manifest import (
    ExecutionManifestGenerationError,
    generate_execution_manifest,
)
from conformance.configuration_contracts.v2_loader import (
    dump_execution_manifest,
    dump_participant_plan,
    dump_resolved_plan,
    dump_suite_policy,
    dump_test_definition_catalogue,
    execution_manifest_id,
    execution_manifest_to_document,
    load_execution_manifest,
    load_participant_plan,
    load_resolved_plan,
    load_suite_policy,
    load_suite_release,
    load_test_definition_catalogue,
    parse_execution_manifest,
    parse_participant_plan,
    parse_resolved_plan,
    parse_suite_policy,
    parse_suite_release,
    parse_test_definition_catalogue,
    participant_plan_to_document,
    resolved_plan_to_document,
    suite_policy_to_document,
    test_definition_catalogue_to_document,
    validate_bundled_schemas,
    validate_catalogue_references,
)
from conformance.configuration_contracts.v2_models import (
    ExecutionManifest,
    ExecutionManifestProvenance,
    ExecutionManifestStep,
    ParticipantPlan,
    ResolvedEndpoint,
    ResolvedPlan,
    ResolvedPlanProvenance,
    ResolvedPredefinedInput,
    ResolvedTestInstance,
    Specification,
    SuitePolicy,
    TestApplicability,
    TestDefinition,
    TestDefinitionCatalogue,
    TestDefinitionRequest,
)

V2CompilationFindingCode = CompilationFindingCode
V2ExecutionManifestGenerationError = ExecutionManifestGenerationError
V2ParticipantPlanCompilationError = ParticipantPlanCompilationError
compile_participant_plan_v2 = compile_participant_plan
dump_execution_manifest_v2 = dump_execution_manifest
dump_participant_plan_v2 = dump_participant_plan
dump_resolved_plan_v2 = dump_resolved_plan
dump_suite_policy_v2 = dump_suite_policy
dump_test_definition_catalogue_v2 = dump_test_definition_catalogue
generate_execution_manifest_v2 = generate_execution_manifest
load_execution_manifest_v2 = load_execution_manifest
load_participant_plan_v2 = load_participant_plan
load_resolved_plan_v2 = load_resolved_plan
load_suite_policy_v2 = load_suite_policy
load_suite_release_v2 = load_suite_release
load_test_definition_catalogue_v2 = load_test_definition_catalogue
parse_execution_manifest_v2 = parse_execution_manifest
parse_participant_plan_v2 = parse_participant_plan
parse_resolved_plan_v2 = parse_resolved_plan
parse_suite_policy_v2 = parse_suite_policy
parse_suite_release_v2 = parse_suite_release
parse_test_definition_catalogue_v2 = parse_test_definition_catalogue
resolve_participant_plan_v2 = resolve_participant_plan
suite_policy_to_document_v2 = suite_policy_to_document
validate_bundled_schemas_v2 = validate_bundled_schemas

__all__ = [
    "ArtifactReference",
    "Capability",
    "CompilationFinding",
    "CompilationFindingCode",
    "ConfigurationContractError",
    "ConfigurationDiagnostic",
    "DetachedJwsOmittedClaim",
    "DetachedJwsProfile",
    "DetachedJwsSource",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "Endpoint",
    "EvidenceMode",
    "ExecutionDetachedJws",
    "ExecutionEvidencePolicy",
    "ExecutionManifest",
    "ExecutionManifestAssertion",
    "ExecutionManifestGenerationError",
    "ExecutionManifestHeader",
    "ExecutionManifestInput",
    "ExecutionManifestProvenance",
    "ExecutionManifestRequest",
    "ExecutionManifestStep",
    "ExecutionPsuAuthorization",
    "ExecutionResponseSignature",
    "ExecutionTokenEndpointAuth",
    "FindingSeverity",
    "FindingSourceDocument",
    "GeneratedHeaderValue",
    "GeneratedValueStrategy",
    "HttpMethod",
    "InputResolutionSource",
    "LegacyExecutionEngine",
    "ParticipantExecutionConfiguration",
    "ParticipantInput",
    "ParticipantPlan",
    "ParticipantPlanCompilationError",
    "PredefinedInput",
    "PredefinedInputValue",
    "PreparedExecutionManifest",
    "RequestBaseUrlSource",
    "RequestInputBinding",
    "RequestModification",
    "RequestStateBinding",
    "ResolutionReason",
    "ResolvedCapability",
    "ResolvedEndpoint",
    "ResolvedPlan",
    "ResolvedPlanAdapterError",
    "ResolvedPlanProvenance",
    "ResolvedPredefinedInput",
    "ResolvedSuiteArtifact",
    "ResolvedTestInstance",
    "ResponseSignatureSource",
    "SelectionOrigin",
    "Sha256Digest",
    "Specification",
    "StableId",
    "StandingOrderFrequency",
    "SuiteRelease",
    "SuitePolicy",
    "SuiteReleaseArtifactError",
    "SuiteReleaseArtifactErrorCode",
    "SuiteReleaseArtifactResolver",
    "TechnicalSource",
    "TestApplicability",
    "TestAssertion",
    "TestDefinition",
    "TestDefinitionCatalogue",
    "TestDefinitionRequest",
    "TestOutput",
    "TokenEndpointAuthSource",
    "ToolRelease",
    "V2CompilationFindingCode",
    "V2ExecutionManifestGenerationError",
    "V2ParticipantPlanCompilationError",
    "compile_participant_plan",
    "compile_participant_plan_v2",
    "dump_execution_manifest",
    "dump_execution_manifest_v2",
    "dump_participant_plan",
    "dump_participant_plan_v2",
    "dump_resolved_plan",
    "dump_resolved_plan_v2",
    "dump_suite_policy",
    "dump_suite_policy_v2",
    "dump_test_definition_catalogue",
    "dump_test_definition_catalogue_v2",
    "execution_manifest_id",
    "execution_manifest_to_document",
    "generate_execution_manifest",
    "generate_execution_manifest_v2",
    "load_execution_manifest",
    "load_execution_manifest_v2",
    "load_participant_plan",
    "load_participant_plan_v2",
    "load_resolved_plan",
    "load_resolved_plan_v2",
    "load_suite_policy",
    "load_suite_policy_v2",
    "load_suite_release",
    "load_suite_release_v2",
    "load_test_definition_catalogue",
    "load_test_definition_catalogue_v2",
    "parse_execution_manifest",
    "parse_execution_manifest_v2",
    "parse_participant_plan",
    "parse_participant_plan_v2",
    "parse_resolved_plan",
    "parse_resolved_plan_v2",
    "parse_suite_policy",
    "parse_suite_policy_v2",
    "parse_suite_release",
    "parse_suite_release_v2",
    "parse_test_definition_catalogue",
    "parse_test_definition_catalogue_v2",
    "participant_plan_to_document",
    "preflight_suite_release_artifacts",
    "resolve_participant_plan",
    "resolve_participant_plan_v2",
    "suite_policy_to_document",
    "suite_policy_to_document_v2",
    "resolved_plan_to_document",
    "test_definition_catalogue_to_document",
    "validate_bundled_schemas",
    "validate_bundled_schemas_v2",
    "validate_catalogue_references",
    "validate_execution_manifest_compatibility",
]
