"""Versioned configuration contracts for the replacement plan architecture."""

from conformance.configuration_contracts.compiled_plan_adapter import (
    LegacyExecutionEngine,
    PreparedExecutionManifest,
    ResolvedPlanAdapterError,
    materialize_execution_manifest_requests,
    validate_execution_manifest_compatibility,
)
from conformance.configuration_contracts.compiler import (
    CompilationFindingCode,
    ParticipantPlanCompilationError,
    compile_participant_plan,
    resolve_participant_plan,
)
from conformance.configuration_contracts.diagnostics import (
    ConfigurationContractError,
    ConfigurationDiagnostic,
    DiagnosticCode,
    DiagnosticSeverity,
)
from conformance.configuration_contracts.execution_manifest import (
    ExecutionManifestGenerationError,
    generate_execution_manifest,
)
from conformance.configuration_contracts.loader import (
    CATALOGUE_SCHEMA_VERSION,
    EXECUTION_MANIFEST_SCHEMA_VERSION,
    PLAN_SCHEMA_VERSION,
    SUITE_RELEASE_SCHEMA_VERSION,
    dump_execution_manifest,
    dump_participant_plan,
    dump_requirements_catalogue,
    dump_resolved_plan,
    dump_suite_release,
    dump_test_definition_catalogue,
    execution_manifest_id,
    execution_manifest_to_document,
    load_execution_manifest,
    load_participant_plan,
    load_requirements_catalogue,
    load_resolved_plan,
    load_suite_release,
    load_test_definition_catalogue,
    parse_execution_manifest,
    parse_participant_plan,
    parse_requirements_catalogue,
    parse_resolved_plan,
    parse_suite_release,
    parse_test_definition_catalogue,
    participant_plan_to_document,
    requirements_catalogue_to_document,
    resolved_plan_to_document,
    suite_release_to_document,
    test_definition_catalogue_to_document,
    validate_bundled_schemas,
    validate_catalogue_references,
    verify_suite_release_artifacts,
)
from conformance.configuration_contracts.models import (
    ArtifactReference,
    Capability,
    CompilationFinding,
    DetachedJwsOmittedClaim,
    DetachedJwsProfile,
    DetachedJwsSource,
    Endpoint,
    EvidenceMode,
    ExecutionDetachedJws,
    ExecutionEvidencePolicy,
    ExecutionManifest,
    ExecutionManifestAssertion,
    ExecutionManifestHeader,
    ExecutionManifestInput,
    ExecutionManifestProvenance,
    ExecutionManifestRequest,
    ExecutionManifestStep,
    ExecutionPsuAuthorization,
    ExecutionResponseSignature,
    ExecutionTokenEndpointAuth,
    FindingSeverity,
    FindingSourceDocument,
    GeneratedHeaderValue,
    GeneratedValueStrategy,
    HttpMethod,
    InputResolutionSource,
    NormativeReference,
    ParticipantExecutionConfiguration,
    ParticipantInput,
    ParticipantPlan,
    PredefinedInput,
    PredefinedInputValue,
    RequestBaseUrlSource,
    RequestInputBinding,
    RequestModification,
    RequestStateBinding,
    Requirement,
    RequirementRule,
    RequirementsCatalogue,
    RequirementTargetType,
    ResolutionReason,
    ResolvedCapability,
    ResolvedEndpoint,
    ResolvedPlan,
    ResolvedPlanProvenance,
    ResolvedPredefinedInput,
    ResolvedRequirement,
    ResolvedTestInstance,
    ResponseSignatureSource,
    SelectionOrigin,
    Sha256Digest,
    SpecificationReference,
    StableId,
    StandingOrderFrequency,
    SuiteRelease,
    TechnicalSource,
    TestAssertion,
    TestDefinition,
    TestDefinitionCatalogue,
    TestOutput,
    TestRequest,
    TokenEndpointAuthSource,
    ToolRelease,
)
from conformance.configuration_contracts.suite_release_artifacts import (
    ResolvedSuiteArtifact,
    SuiteReleaseArtifactError,
    SuiteReleaseArtifactErrorCode,
    SuiteReleaseArtifactResolver,
    preflight_suite_release_artifacts,
)
from conformance.configuration_contracts.v2_compiler import (
    CompilationFindingCode as V2CompilationFindingCode,
)
from conformance.configuration_contracts.v2_compiler import (
    ParticipantPlanCompilationError as V2ParticipantPlanCompilationError,
)
from conformance.configuration_contracts.v2_compiler import (
    compile_participant_plan as compile_participant_plan_v2,
)
from conformance.configuration_contracts.v2_compiler import (
    resolve_participant_plan as resolve_participant_plan_v2,
)
from conformance.configuration_contracts.v2_execution_manifest import (
    ExecutionManifestGenerationError as V2ExecutionManifestGenerationError,
)
from conformance.configuration_contracts.v2_execution_manifest import (
    generate_execution_manifest as generate_execution_manifest_v2,
)
from conformance.configuration_contracts.v2_loader import (
    dump_execution_manifest as dump_execution_manifest_v2,
)
from conformance.configuration_contracts.v2_loader import (
    dump_participant_plan as dump_participant_plan_v2,
)
from conformance.configuration_contracts.v2_loader import (
    dump_resolved_plan as dump_resolved_plan_v2,
)
from conformance.configuration_contracts.v2_loader import (
    dump_test_definition_catalogue as dump_test_definition_catalogue_v2,
)
from conformance.configuration_contracts.v2_loader import (
    load_execution_manifest as load_execution_manifest_v2,
)
from conformance.configuration_contracts.v2_loader import (
    load_participant_plan as load_participant_plan_v2,
)
from conformance.configuration_contracts.v2_loader import (
    load_resolved_plan as load_resolved_plan_v2,
)
from conformance.configuration_contracts.v2_loader import (
    load_suite_release as load_suite_release_v2,
)
from conformance.configuration_contracts.v2_loader import (
    load_test_definition_catalogue as load_test_definition_catalogue_v2,
)
from conformance.configuration_contracts.v2_loader import (
    parse_execution_manifest as parse_execution_manifest_v2,
)
from conformance.configuration_contracts.v2_loader import (
    parse_participant_plan as parse_participant_plan_v2,
)
from conformance.configuration_contracts.v2_loader import (
    parse_resolved_plan as parse_resolved_plan_v2,
)
from conformance.configuration_contracts.v2_loader import (
    parse_suite_release as parse_suite_release_v2,
)
from conformance.configuration_contracts.v2_loader import (
    parse_test_definition_catalogue as parse_test_definition_catalogue_v2,
)
from conformance.configuration_contracts.v2_loader import (
    validate_bundled_schemas as validate_bundled_schemas_v2,
)

__all__ = [
    "ArtifactReference",
    "CATALOGUE_SCHEMA_VERSION",
    "Capability",
    "CompilationFinding",
    "CompilationFindingCode",
    "ConfigurationContractError",
    "ConfigurationDiagnostic",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "DetachedJwsOmittedClaim",
    "DetachedJwsProfile",
    "DetachedJwsSource",
    "EXECUTION_MANIFEST_SCHEMA_VERSION",
    "Endpoint",
    "EvidenceMode",
    "ExecutionDetachedJws",
    "ExecutionEvidencePolicy",
    "ExecutionManifestHeader",
    "ExecutionManifest",
    "ExecutionManifestAssertion",
    "ExecutionManifestGenerationError",
    "ExecutionManifestInput",
    "ExecutionManifestProvenance",
    "ExecutionManifestRequest",
    "ExecutionManifestStep",
    "ExecutionPsuAuthorization",
    "ExecutionResponseSignature",
    "ExecutionTokenEndpointAuth",
    "FindingSeverity",
    "FindingSourceDocument",
    "GeneratedHeaderValue",
    "GeneratedValueStrategy",
    "HttpMethod",
    "InputResolutionSource",
    "LegacyExecutionEngine",
    "NormativeReference",
    "PLAN_SCHEMA_VERSION",
    "PreparedExecutionManifest",
    "ParticipantInput",
    "ParticipantExecutionConfiguration",
    "ParticipantPlan",
    "ParticipantPlanCompilationError",
    "PredefinedInput",
    "PredefinedInputValue",
    "RequestInputBinding",
    "RequestBaseUrlSource",
    "RequestModification",
    "RequestStateBinding",
    "ResolutionReason",
    "ResolvedCapability",
    "ResolvedEndpoint",
    "ResolvedPlan",
    "ResolvedPlanAdapterError",
    "ResolvedPlanProvenance",
    "ResolvedPredefinedInput",
    "ResolvedRequirement",
    "ResolvedTestInstance",
    "ResolvedSuiteArtifact",
    "ResponseSignatureSource",
    "Requirement",
    "RequirementRule",
    "RequirementTargetType",
    "RequirementsCatalogue",
    "SUITE_RELEASE_SCHEMA_VERSION",
    "Sha256Digest",
    "SelectionOrigin",
    "SpecificationReference",
    "StableId",
    "StandingOrderFrequency",
    "SuiteRelease",
    "SuiteReleaseArtifactError",
    "SuiteReleaseArtifactErrorCode",
    "SuiteReleaseArtifactResolver",
    "TechnicalSource",
    "TestAssertion",
    "TestDefinition",
    "TestDefinitionCatalogue",
    "TestOutput",
    "TestRequest",
    "TokenEndpointAuthSource",
    "ToolRelease",
    "materialize_execution_manifest_requests",
    "compile_participant_plan",
    "dump_execution_manifest",
    "dump_participant_plan",
    "dump_requirements_catalogue",
    "dump_resolved_plan",
    "dump_suite_release",
    "dump_test_definition_catalogue",
    "execution_manifest_id",
    "execution_manifest_to_document",
    "generate_execution_manifest",
    "load_execution_manifest",
    "load_requirements_catalogue",
    "load_participant_plan",
    "load_resolved_plan",
    "load_suite_release",
    "load_test_definition_catalogue",
    "parse_execution_manifest",
    "parse_requirements_catalogue",
    "parse_participant_plan",
    "parse_resolved_plan",
    "parse_suite_release",
    "parse_test_definition_catalogue",
    "preflight_suite_release_artifacts",
    "requirements_catalogue_to_document",
    "participant_plan_to_document",
    "resolved_plan_to_document",
    "resolve_participant_plan",
    "suite_release_to_document",
    "test_definition_catalogue_to_document",
    "validate_bundled_schemas",
    "validate_catalogue_references",
    "validate_execution_manifest_compatibility",
    "verify_suite_release_artifacts",
    "V2CompilationFindingCode",
    "V2ExecutionManifestGenerationError",
    "V2ParticipantPlanCompilationError",
    "compile_participant_plan_v2",
    "dump_execution_manifest_v2",
    "dump_participant_plan_v2",
    "dump_resolved_plan_v2",
    "dump_test_definition_catalogue_v2",
    "generate_execution_manifest_v2",
    "load_execution_manifest_v2",
    "load_participant_plan_v2",
    "load_resolved_plan_v2",
    "load_suite_release_v2",
    "load_test_definition_catalogue_v2",
    "parse_execution_manifest_v2",
    "parse_participant_plan_v2",
    "parse_resolved_plan_v2",
    "parse_suite_release_v2",
    "parse_test_definition_catalogue_v2",
    "resolve_participant_plan_v2",
    "validate_bundled_schemas_v2",
]
